### ISSUE TITLE
Client code VS project should reference relative to project file, not solution file.

### ISSUE THREAD

**Issue by ngaloppo** [deplinenoise/ig-memtrace#1]
When integrating the client code by adding Memtrace.vcxproj to an existing solution file, the client code fails to compile because it can't find minhook.h. This is because the include path is referring to `$(SolutionDir)..\minhook`. This should be changed to `$(ProjectDir)..\minhook`.

**Comment by deplinenoise** [comment]
That's not how you integrate the client code though - it needs to be integrated by copying the files to your root executable, because it has a static initializer that runs before the CRT stuff.
