### ISSUE TITLE
No fragmentation data for CRT heap

### ISSUE THREAD

**Issue by gjaegy** [deplinenoise/ig-memtrace#2]
Hi,
our project is using VS2013 and is a 32-bits program (x86). I have successfully managed to compile minihook to get the x86 version of the DLL.

I have modified three lines of MemTrace.cpp:

 if (HMODULE minhook_module = LoadLibraryA("MinHook.x86.dll"))

and
# if _MSC_VER != 1800

and

  if (HMODULE crt_module = GetModuleHandleA("msvcr120.dll"))

I have then integrated MemTrace using the mechanism provided by MemTraceInit.h.

It seems to be working.
![2015-07-07 10_17_04-trace_130807302358522109 mtrace windows - 19 100 088 events - memtrace heap vi](https://cloud.githubusercontent.com/assets/900305/8541896/afbcd6ca-2491-11e5-9571-e193872b2c37.png)

However, the fragmentation view is empty. Any idea how I can fix that ? What have I missed ?

![2015-07-07 10_17_47-trace_130807302358522109 mtrace windows - 19 100 088 events - memtrace heap vi](https://cloud.githubusercontent.com/assets/900305/8541907/c95f72ae-2491-11e5-912b-6df43d65b8fd.png)

thanks a lot !!

Greg

**Comment by deplinenoise** [comment]
Fragmentation data isn't available for the CRT heap, because MemTrace doesn't currently know what all the memory blocks it allocates are.

**Comment by gjaegy** [comment]
Thanks for the information Andreas.

So, what would you recommend, what can I do to see the global fragmentation, is there any way to achieve that ?

Thanks !

Greg

**Comment by deplinenoise** [comment]
If your application allows, the easiest way would be to switch out the CRT heap for a different heap implementation, and then integrate that with MemTrace. TLSF is one good option, but there are several others depending on what your needs are. If you really want to stick with the CRT heap (why?!) then you might consider just switching for a memory tracing build.

I'm not sure what you'd need to do to track all the internals of the CRT heap, but it probably involves quite a bit of reverse engineering and/or delving into CRT source code.

**Comment by gjaegy** [comment]
Actually we’ve never really done anything related to memory, but are facing issues right now ;)

I will have a look at TLSF. I was considering ltalloc (https://code.google.com/p/ltalloc/), but since you recommend TLSF, we will investigate that one as well.

So, in the case we switch to TLSF (I assume we’ll have to override the new & delete operators to rely on TLSF – no idea how to handle the allocation performed by the external dependencies we use), what is left to be done to have the fragmentation view working ? I assume I simply have to modify the allocator in order to have the functions described in the “Instrumenting Custom Allocators” chapter called ? Is that right ?

Cheers

Greg

**Comment by deplinenoise** [comment]
Sorry I took so long to respond - this project had fallen off my radar. To answer the question, in case it's helpful for someone - yes, you instrument your allocator as described in the docs.
