### ISSUE TITLE
Q. What are AddressAllocate/AddressFree for?

### ISSUE THREAD

**Issue by uucidl** [deplinenoise/ig-memtrace#5]
There's no word for it in the header file, the relationship between HeapAllocate and AddressAllocate is unclear.

**Comment by deplinenoise** [comment]
`AddressAllocate` notifies the tracker of virtual address space ranges. Heaps then grab blocks from these ranges. This is required to get fragmentation views working. Without address range info, the fragmentation view is disabled (e.g. for the default Windows CRT heap).
