### ISSUE TITLE
Wrapped__aligned_malloc

### ISSUE THREAD

**Issue by gjaegy** [deplinenoise/ig-memtrace#7]
Hi, 

in my reports, I have many branches ending up with a Wrapped__aligned_malloc / Wrapper__aligned_offset_malloc pair.

Which means I have no clue who is the author of that kind of aligned allocations.

I there any way to get further information for that type of allocations ?

thanks a lot
Greg

**Comment by deplinenoise** [comment]
I'm not sure I understand the question. You should be able to see the callstack that leads to `_aligned_malloc` being called.
