### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by gjaegy** [deplinenoise/ig-memtrace#8]
Hi, me again :)
I am encountering a new issue when opening a trace file. Not sure what is causing that, I assume there is something wrong in our code, but no idea what:

![image](https://user-images.githubusercontent.com/900305/35681224-02570f94-075d-11e8-81b4-e907a4be956f.png)

I can successfully fix that by modifying BuildBackTraceNodes(), by simply encapsulatingthe function code in:
` if (frames.Count > 0)
{
.....
}`

Still, I would be interested in getting some clue of what's going on...

Thanks for any input !

**Comment by deplinenoise** [comment]
Which index is out of range? It looks like the file contains garbage data.
